version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8091'
    - --scheme
    - http
    image: gsi/weaviate
    network_mode: host # works on Linux but not Mac
    volumes:
      - /var/lib/weaviate:/var/lib/weaviate
      - /home/public:/home/public
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://localhost:8080'
      CLUSTER_HOSTNAME: 'node1'
      GEMINI_ALLOCATION_ID: 'fd283b38-3e4a-11eb-a205-7085c2c5e516'
      GEMINI_DATA_DIRECTORY: '/home/public' 
      GEMINI_FVS_SERVER: 'localhost' 
      GEMINI_DEBUG: 'false'
  t2v-transformers:
    image: gsi/t2v
    network_mode: host # works on Linux not Mac
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia # assumes you have an NVidia GPU
            count: 1
            capabilities: [gpu] 
    environment:
      ENABLE_CUDA: 1 # assumes you have an NVidia GPU
