version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8091'
    - --scheme
    - http
    image: gsi/weaviate
    ports:
    - 8091:8091
    volumes:
      - /var/lib/weaviate:/var/lib/weaviate
    restart: "no"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://bench2v:8080'
      CLUSTER_HOSTNAME: 'node1'
  bench2v:
    image: gsi/bench2v 
    ports:
     - "8080:8080"
    volumes:
#     - /mnt/nas1/fvs_benchmark_datasets:/datasets
     - /Users/gwilliams/Projects/GSI/Weaviate/data:/datasets
    restart: "no"
    environment:
      VERBOSE: 0
      ENABLE_CUDA: 0
      DATABASE_FILE: "/datasets/deep-10K.npy"
      QUERY_FILE: "/datasets/deep-queries-1000.npy"
      GROUND_TRUTH_FILE: "/datasets/deep-10K-gt-1000.npy"
