version: '3.4'
services:
  bench2v:
    image: gsi/bench2v 
    ports:
     - "8080:8080"
    volumes:
     - /mnt/nas1/fvs_benchmark_datasets:/datasets
#     - /Users/gwilliams/Projects/GSI/Weaviate/data:/datasets
    restart: "no"
    environment:
      VERBOSE: 1
      ENABLE_CUDA: 0
      DATABASE_FILE: "/datasets/deep-10K.npy"
      QUERY_FILE: "/datasets/deep-queries-1000.npy"
      GROUND_TRUTH_FILE: "/datasets/deep-10K-gt-1000.npy"
