version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8091'
    - --scheme
    - http
    image: gsi/weaviate
    volumes:
      - /var/lib/weaviate:/var/lib/weaviate
      - /home/public:/home/public
    network_mode: host
    restart: "no"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://localhost:8080'
      CLUSTER_HOSTNAME: 'node1'
      DEFAULT_VECTOR_INDEX_TYPE: 'gemini'
      GEMINI_ALLOCATION_ID: '0b391a1a-b916-11ed-afcb-0242ac1c0002'
      GEMINI_DATA_DIRECTORY: '/home/public'
      GEMINI_FVS_SERVER: 'localhost'
      GEMINI_DEBUG: 'false'
      GEMINI_MIN_RECORDS_CHECK: 'true'
  bench2v:
    image: gsi/bench2v 
    volumes:
     - /mnt/nas1/fvs_benchmark_datasets:/datasets
#     - /Users/gwilliams/Projects/GSI/Weaviate/data:/datasets
    network_mode: host
    restart: "no"
    environment:
      VERBOSE: 0
      ENABLE_CUDA: 0
      DATABASE_FILE: "/datasets/deep-10K.npy"
      QUERY_FILE: "/datasets/deep-queries-1000.npy"
      GROUND_TRUTH_FILE: "/datasets/deep-10K-gt-1000.npy"
