version: '3.4'
services:
  bench2v:
    image: gsi/bench2v 
    ports:
     - "8080:8080"
    volumes:
     - /Users/gwilliams/Projects/GSI/Weaviate/data/:/datasets
    environment:
      ENABLE_CUDA: 0
      NUMPY_FILE: "/datasets/deep-1M.npy"
  fake_fvs:
    image: gsi/fake_fvs
    ports:
    - "7761:7761"
    volumes:
      - /var/lib/weaviate:/var/lib/weaviate

