name: golangci-lint
on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - uses: actions/checkout@v3
      - run: |
          go mod edit -replace github.com/gsi/weaviate/gemini_plugin=./gsi/weaviate_gemini_plugin
          go mod tidy
          go get github.com/gsi/weaviate/gemini_plugin
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.51
          args: --timeout=3m
